server:
  port:8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: bamboo-consumer
  freemarker:
    prefer-file-system-access: false
  jpa:
    # ָ����Spring��������ʱ�Ƿ��Զ�����Ĭ��Ϊfalse
    generate-ddl: true
    # ָ���Ƿ��ڿ���̨��ʾ��ִ�е�SQL��䣬Ĭ��false
    show-sql: true
    # ָ��Ӧ������ʱ�Ƿ����´������±�
    hibernate:
      ddl-auto: none
  # ��������Դ
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///coffeebaby?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
logging:
  # ������־�����ʽ
  pattern:
    console: level-%level %msg%n
  level:
    root: info   # ����Spring Boot����ʱ����־����

    org.hibernate: info   # ����hibernate����ʱ����־����
    # ��show-sqlΪtrueʱ����ʾSQL�еĶ�̬����ֵ
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # ��show-sqlΪtrueʱ����ʾSQL��ѯ���
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

    com.abc.provider: debug
info:
  auth: victor
  app.name: bamboo
  app.desc: This is bamboo.
  company.name: www.bamboo.com
  company.addr: Beijing China
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        # Feign�����ṩ�߳�ʱʱ�ޣ� ����������״��Ӱ��
        connectTimeout: 5000
        # Feign�����ṩ��Ӧ�ĳ�ʱʱ�ޣ� �����ڷ���������ʱ��
        readTimeout: 5000
  compression:
    request:
      # �����������ѹ��
      enabled: true
      # ָ��ѹ��MIME�ļ�����
      mime-types: ["text/xml", "application/xml", "application/json"]
      # ָ������ѹ������С�ļ���С����λ�ֽ�
      min-request-size: 2048
    response:
      # �����Կͻ�����Ӧ��ѹ��
      enabled: true

# �޸ĸ��ؾ������
# Ҫ���ؾ�����ṩ��΢��������
#bamboo-provider:
  # ָ��Ҫʹ�õĸ��ؾ������
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
